# Generated by Django 3.1.4 on 2023-02-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Page heading', max_length=30)),
                ('ingress', models.CharField(help_text='ingress text', max_length=100)),
            ],
            options={
                'ordering': ['-heading'],
            },
        ),
    ]
