# Generated by Django 3.1.4 on 2023-03-07 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=30)),
                ('text', models.CharField(max_length=30)),
                ('music', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('v', 'Viser'), ('h', 'Hip hop')], max_length=1)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
