# Generated by Django 3.1.4 on 2023-03-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='AllSong',
        ),
    ]
