# Generated by Django 3.1.4 on 2023-03-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title of song', max_length=20)),
                ('song_text', models.TextField(max_length=2000)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
