# Generated by Django 3.1.4 on 2023-03-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_text',
            field=models.TextField(max_length=2000),
        ),
    ]
