# Generated by Django 4.1.7 on 2023-07-06 21:42

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of participant', max_length=30)),
                ('points', django_mysql.models.ListTextField(models.IntegerField(help_text='Points per game'), size=10)),
            ],
        ),
    ]
