# Generated by Django 4.1.7 on 2023-07-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='bonuspoeng',
            field=models.IntegerField(blank=True, help_text='Points for bonuspoeng', null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='bordtennis',
            field=models.IntegerField(blank=True, help_text='Points for bordtennis', null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='fifa',
            field=models.IntegerField(blank=True, help_text='Points for fifa', null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='foccia',
            field=models.IntegerField(blank=True, help_text='Points for foccia', null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='gulbolle',
            field=models.IntegerField(blank=True, help_text='Points for gulbolle', null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='kaptein',
            field=models.IntegerField(blank=True, help_text='Points for kaptein', null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='klinkbong',
            field=models.IntegerField(blank=True, help_text='Points for klinkbong', null=True),
        ),
    ]
