# Generated by Django 3.1.4 on 2023-03-08 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_song_release_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_data',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 8, 19, 48, 3, 995992)),
        ),
    ]
