# Generated by Django 4.1.7 on 2023-07-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_tasks_alter_participants_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, help_text='description', null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='matches',
            field=models.TextField(blank=True, help_text='matches', null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='points',
            field=models.TextField(blank=True, help_text='points', null=True),
        ),
    ]
