# Generated by Django 3.1.4 on 2023-03-08 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20230308_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_data',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 8, 19, 50, 15, 611799)),
        ),
    ]
